### ISSUE TITLE
Callback not firing

### ISSUE THREAD

**Issue by ksabariraj** [ShawnFoo/SwiftWebViewBridge#4]
Hi,

Thanks for the code. 

when I'm trying to run your code always default callback is executing. Can you please help me on this?

Thanks.

**Comment by ShawnFoo** [comment]
Hi,
I have downloaded and tested my latest release from git(Builded on Xcode7.3.1). But couldn't repeat your case.

Could you please offer more infos? 
For example. Is it always executing default callback on the Swift side or on the other side?
Snapshots will be more helpful : ]

By the way, If you just call methods sending data  between Swift and Javascript rather than call registered handlers, that will only trigger default handler since handler is used to deal with 'designated job' and for which you don't designate will be passed through default handler.

Thank you

**Comment by ksabariraj** [comment]
Hi,

Thanks for the quick update.

I am using Version 7.2.1 (7C1002). 

Please find the attachment.

<img width="832" alt="screen shot 2016-07-29 at 10 13 49 am" src="https://cloud.githubusercontent.com/assets/3765085/17270558/de4f07d2-5682-11e6-9715-215fedef04e8.png">
<img width="420" alt="screen shot 2016-07-29 at 10 14 24 am" src="https://cloud.githubusercontent.com/assets/3765085/17270559/de508ae4-5682-11e6-9914-8e12fbfcb5e0.png">
<img width="751" alt="screen shot 2016-07-29 at 10 14 47 am" src="https://cloud.githubusercontent.com/assets/3765085/17270557/de4715d6-5682-11e6-8e34-bb94ca8743ac.png">
<img width="828" alt="screen shot 2016-07-29 at 10 15 09 am" src="https://cloud.githubusercontent.com/assets/3765085/17270556/de453068-5682-11e6-9d93-b59879e35edc.png">

Thanks.

**Comment by ShawnFoo** [comment]
IMO, I think you did build and run the project, but you didn't click other buttons to call handler registered on both Swift and Javascript side.
The only reason why return default handler every time is this statement in ViewDidLoad method.
```
self.bridge.sendDataToJS(["msg": "Hello JavaScript, My name is 小明", "gift": ["100CNY", "1000CNY", "10000CNY"]])
```
![qq20160731-0](https://cloud.githubusercontent.com/assets/8295070/17276075/296e6f82-5750-11e6-8fb9-6f16ac09a6d5.png)
![2](https://cloud.githubusercontent.com/assets/8295070/17276077/31f215aa-5750-11e6-93d3-b553d24de4b7.png)

**Comment by ksabariraj** [comment]
Hi,

Thanks for your details.

I tried both end. but, still the callback is not firing.

I am receiving message and **responseId** in data, but, when check `if let responseId = swvbMsg["responseId"] as? String {` it's failed.

Can you please guide on this?

Note: I tried all function in both javascript and swift. All function failed in the same condition mentioned above.

Thanks,
Sabari.

**Comment by ShawnFoo** [comment]
Hi,
Try on these steps to see if program will run to this statement below

```
return self.messageHandlers[handlerName]
```
1. Set up two break points firstly
   ![1](https://cloud.githubusercontent.com/assets/8295070/17295427/a6f3acc2-582e-11e6-9011-30770579064f.png)
2. Then, click one of these buttons
   ![qq20160804-0](https://cloud.githubusercontent.com/assets/8295070/17374045/7153e20c-59dd-11e6-9b7b-19933da78076.png)

Since calling this method **SwiftWebViewBridge.callSwiftHandler("printReceivedParmas", data, null)** from the Javascript will send a message carried these infos below.
The handlerName, 'printReceivedParmas', is the name of handler registered on Swift side

```
{
        callbackId = "cb_1_JS_1470057761845";
        data =         {
            age = 6;
            name = "\U5c0f\U660e";
            school = GDUT;
        };
        handlerName = printReceivedParmas;
}
```

So when Swift run into handleMessagesFromJS method, it will check message sent from JS if it designate a handle to deal with it. If no handlerName or not existed, then return defaultHandler at the end.

---

A More quickier way, just set up a break point at this line and test if Xcode will break in there
![3](https://cloud.githubusercontent.com/assets/8295070/17295739/33f96002-5830-11e6-8948-2512c4498821.png)
